### ISSUE TITLE
Logging to Elasticsearch is not working with docker image

### ISSUE THREAD

**Issue by sanjyotagureddy** [sanjyotagureddy/dotnetcore-monitoring#6]
Logging to Elastic search work fine when connected to localhost app connection to elasticsearch url at https://localhost:9200, but it fails to connect with docker images of the Api to the docker image of Elastic search at http://elasticsearch:9200

![image](https://user-images.githubusercontent.com/16202971/200195084-9c3f0f41-976c-4945-b88f-4fd508a794f9.png)

**Comment by alperozoner** [comment]
You should create a new kernel of the docker images and access them from https://localhost:9200/

**Comment by sanjyotagureddy** [comment]
@alperozoner how can I do that ?

**Comment by alperozoner** [comment]
Look up creating kernels for the environment from documents.

**Comment by sanjyotagureddy** [comment]
@alperozoner didn't work
